# 
# Outputs for the Terraform module.
#
# This file might be generated by the `terraform-docs` tool as well. 
# It contains the outputs that are generated by the Terraform module.
# These outputs can be used by other Terraform modules or scripts.
# The output block contains the name of the output, a description, and the value of the output.
# The value of the output can be a variable, a resource attribute, or a function.
# The output value can be used in other Terraform modules or scripts.
#
