name: Debug context

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ##############################################################################
  ##
  ## Debug job
  ##
  ##############################################################################

  Debug_Context:
    name: Debug received context
    runs-on: ubuntu-latest
    # runs-on: ["self-hosted", "m92p"] # Only for organization runners
    environment: ci_cd_pipeline

    steps:
      - name: Dump Github context
        run: |
          echo '${{ '-----------------------------------------------------' }}'
          echo '${{ 'Event' }}'
          echo '${{ toJSON(github.event) }}'
          
          echo '${{ '-----------------------------------------------------' }}'
          echo '${{ 'Run ID & Number' }}'
          echo '${{ toJSON(github.run_id) }}'
          echo '${{ toJSON(github.run_number) }}'
          
          echo '${{ '-----------------------------------------------------' }}'
          echo '${{ 'Workspace & Action' }}'
          echo '${{ toJSON(github.workspace) }}'

